# Generated by Django 5.1.2 on 2024-10-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
